const router = require("express").Router()
const UserController =require("../app/controller/user.controller")
router.post("/register",UserController.register)
router.get("/all",UserController.getAll)
router.get("/single/:id",UserController.getSingle)
router.delete("/delete",UserController.delete)
router.post("/delete/:id" , UserController.deleteOne)
router.post("/edit/:id" , UserController.edit)
router.post("/login",UserController.login)
router.post("/editPass/:id" , UserController.editPass)
const auth = require("../app/middleware/auth")
router.post("/me" , auth , (req , res)=>{
    res.send(user)
})
router.post("/logout", auth , UserController.logout)
router.post("/logoutAll", auth , UserController.logoutAll)
router.post("/editData", auth , UserController.editMyData)
router.post("/activate", auth , UserController.activate)
router.post("/deActivate", auth , UserController.deActivate)
module.exports= router